### ISSUE TITLE
Identify and document end-to-end use cases

### ISSUE THREAD

**Issue by ed-snodgrass** [Call-for-Code-for-Racial-Justice/Truth-Loop#254]
### Background on the problem the feature will solve/improved user experience
We need to understand what behaviors the MVP version of the application should be able to support

### Describe the solution you'd like
In the project wiki we have the Use cases/behaviors documented:

### Tasks:
Add all user stories here: https://github.com/Call-for-Code-for-Racial-Justice/Truth-Loop/wiki
find user stories listed here: #257 

### Acceptance Criteria 
- MVP behaviors are identified and documented
- Details on how to validate those use cases exist

**Comment by demilolu** [comment]
@sharonosahon has provided these use cases. I'll make a new issue on this @ed-snodgrass 
[User stories.xlsx](https://github.com/Call-for-Code-for-Racial-Justice/Truth-Loop/files/8042043/User.stories.xlsx)
.

**Comment by demilolu** [comment]
tasks remaining to add the User Stories to project wiki

Sample information and closing other issue #256 

We need to document the user stories in the .md file so that a new user can understand the expected full functionality of Truth Loop. 

### Describe the solution you'd like
- Add User Stories to readme.md or a userstories.md file

### Tasks 
- See attachment with user stories. 
[User stories.xlsx](https://github.com/Call-for-Code-for-Racial-Justice/Truth-Loop/files/8042090/User.stories.xlsx)

- add user stories to readme.md  a userstories.md file, 
- update file as scope of project changes.

### Acceptance Criteria 
- As a new user I should be able to understand the expected functionality of Truth Loop so that I can understand gaps, create tests etc. 
-  Text should be written and not attached as a separate file

**Comment by ed-snodgrass** [comment]
@demilolu I created a wiki page: https://github.com/Call-for-Code-for-Racial-Justice/Truth-Loop/wiki/User-Stories and added all the stories that @sharonosahon posted in #257 

Should I use the stuff from the spreadsheet to try an create a table or should I just group these by epic?

**Comment by ed-snodgrass** [comment]
Also, I'm not sure if this was the original intent of the end-to-end use cases suggestion but I find this valuable. Were there original user stories/use cases that we should add?
